### PR TITLE
Eve aboutus

### PR DESCRIPTION
**Pull request by evesha**
Resending once again ... pls check about us

### CODE REVIEW

**Review by mpsslh — COMMENTED** [review]
checked

**Review by nirantech — COMMENTED** [review]
Reviewed

**Review by rajalaxmi1 — COMMENTED** [review]
noted about it.

**Review by rajalaxmi1 — APPROVED** [review]
noted it.

**Review by rajalaxmi1 — APPROVED** [review]
noted it.

**Pull request merged**
