### PR TITLE
Beau mainpage navbar placeholder

### PR DESCRIPTION
**Pull request by mpsslh**
navbar with placeholder links

### CODE REVIEW

**Review by rajalaxmi1 — COMMENTED** [review]
navbar changes are noted.

**Review by rajalaxmi1 — COMMENTED** [review]
noted about it

**Review by nirantech — APPROVED** [review]
approved

**Review by evesha — COMMENTED** [review]
All good, thank you for the changes

**Review by evesha — APPROVED** [review]
Approved

**Pull request merged**
